### ISSUE TITLE
"something went wrong"

### ISSUE THREAD

**Issue by dsernst** [beeminder/urlminder#2]
Trying to set up a URLminder for a GH Pages powered Jekyll blog, ran across this error: 
![urlminder something went wrong 500](https://cloud.githubusercontent.com/assets/6340841/3786971/e6ddf744-19f0-11e4-9701-e711571618fc.png)

Tried 3 times, with variations on URL:
* full with http://, CNAMEd redirect
* without http://, CNAMEd redirect
* bare @ github.io domain

Any advice?

**Comment by andrewpbrett** [comment]
Closing along with #3
