### ISSUE TITLE
can't do initial authentication

### ISSUE THREAD

**Issue by dsernst** [beeminder/urlminder#3]
Trying to test URLminder to see if the issue ( #2  ) I opened last month is still open....

Using a new computer and going through the process afresh.

Now can't even make it past the initial "Connect to Beeminder stage".

It's redirecting me to:

http://urlminder.herokuapp.com/auth/failure?message=invalid_credentials&origin=https%3A%2F%2Furlminder.herokuapp.com%2F&strategy=beeminder

With this error:
![screen shot 2014-09-16 at 1 59 51 pm](https://cloud.githubusercontent.com/assets/6340841/4293228/3a25b6ba-3dd4-11e4-91ff-077d6ff11cde.png)

I'm logged into Beeminder. Using stable version Chrome on OS X.

**Comment by andrewpbrett** [comment]
So this is rather embarrassing but this should now be fixed. @dreeves realized that it was working over http but not https, so I updated the config to point to https. Going to close but reopen if it still doesn't work!

**Comment by dsernst** [comment]
Confirmed that I can now get past the *Connect to Beeminder* stage :+1:
